# Generated by Django 2.0.5 on 2019-11-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
